/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GoogleAuthProvider, signInWithPopup } from "firebase/auth";
import { auth, googleProvider, getCachedAccessToken, setCachedAccessToken } from "./firebase";
import { PlannerTask, GoogleCalendarEvent } from "../types";

const CALENDAR_API_BASE = "https://www.googleapis.com/calendar/v3";

/**
 * Retrieves the in-memory access token, or triggers Google Sign-In with Calendar scopes
 * to retrieve a fresh access token. Never stores access token in localStorage/sessionStorage.
 */
export async function ensureCalendarAccessToken(forcePrompt = false): Promise<string> {
  const existingToken = getCachedAccessToken();
  if (existingToken && !forcePrompt) {
    return existingToken;
  }

  // Request token via popup
  const result = await signInWithPopup(auth, googleProvider);
  const credential = GoogleAuthProvider.credentialFromResult(result);
  const token = credential?.accessToken;

  if (!token) {
    throw new Error("Unable to obtain Google Calendar access token from authorization response.");
  }

  setCachedAccessToken(token);
  return token;
}

/**
 * Fetches primary Google Calendar events between start and end dates.
 */
export async function getCalendarEvents(
  startDate: Date,
  endDate: Date
): Promise<GoogleCalendarEvent[]> {
  const token = await ensureCalendarAccessToken();

  const timeMin = encodeURIComponent(startDate.toISOString());
  const timeMax = encodeURIComponent(endDate.toISOString());

  const response = await fetch(
    `${CALENDAR_API_BASE}/calendars/primary/events?timeMin=${timeMin}&timeMax=${timeMax}&singleEvents=true&orderBy=startTime&maxResults=100`,
    {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/json",
      },
    }
  );

  if (response.status === 401) {
    // Token may have expired, force re-authorization
    setCachedAccessToken(null);
    const refreshedToken = await ensureCalendarAccessToken(true);
    const retryResponse = await fetch(
      `${CALENDAR_API_BASE}/calendars/primary/events?timeMin=${timeMin}&timeMax=${timeMax}&singleEvents=true&orderBy=startTime&maxResults=100`,
      {
        headers: {
          Authorization: `Bearer ${refreshedToken}`,
          Accept: "application/json",
        },
      }
    );
    if (!retryResponse.ok) {
      const err = await retryResponse.json().catch(() => ({}));
      throw new Error(err.error?.message || "Failed to load Google Calendar events.");
    }
    const data = await retryResponse.json();
    return data.items || [];
  }

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.error?.message || "Failed to load Google Calendar events.");
  }

  const data = await response.json();
  return data.items || [];
}

/**
 * Creates a new event in the user's primary Google Calendar corresponding to a PlannerTask.
 */
export async function createCalendarEvent(
  task: PlannerTask
): Promise<{ id: string; htmlLink?: string }> {
  const token = await ensureCalendarAccessToken();

  // Construct start and end Date objects in local time zone
  const [year, month, day] = task.date.split("-").map(Number);
  const startDateTime = new Date(year, month - 1, day, task.startHour, 0, 0);
  const endDateTime = new Date(year, month - 1, day, task.endHour, 0, 0);
  const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";

  // Category to calendar colorId mapping (Google Calendar standard colors 1-11)
  const categoryColors: Record<string, string> = {
    work: "9", // Bold blue
    personal: "11", // Bold red / flamingo
    health: "10", // Basil green
    learning: "5", // Banana yellow
    creative: "3", // Grape purple
    general: "7", // Peacock teal
  };

  const payload = {
    summary: `[atom-i] ${task.title}`,
    description: `${task.description || ""}\n\n• Focus Category: ${task.category.toUpperCase()}\n• Priority: ${task.priority.toUpperCase()}\n• Status: ${task.completed ? "COMPLETED" : "PLANNED"}\n\nGenerated by atom-i Tactical Operation Manager`,
    start: {
      dateTime: startDateTime.toISOString(),
      timeZone,
    },
    end: {
      dateTime: endDateTime.toISOString(),
      timeZone,
    },
    colorId: categoryColors[task.category] || "7",
    reminders: {
      useDefault: false,
      overrides: [
        { method: "popup", minutes: 10 },
        { method: "popup", minutes: 2 },
      ],
    },
  };

  const response = await fetch(`${CALENDAR_API_BASE}/calendars/primary/events`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (response.status === 401) {
    setCachedAccessToken(null);
    const refreshedToken = await ensureCalendarAccessToken(true);
    const retryResponse = await fetch(`${CALENDAR_API_BASE}/calendars/primary/events`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${refreshedToken}`,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify(payload),
    });
    if (!retryResponse.ok) {
      const err = await retryResponse.json().catch(() => ({}));
      throw new Error(err.error?.message || "Failed to create Google Calendar event.");
    }
    const data = await retryResponse.json();
    return { id: data.id, htmlLink: data.htmlLink };
  }

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.error?.message || "Failed to create Google Calendar event.");
  }

  const data = await response.json();
  return { id: data.id, htmlLink: data.htmlLink };
}

/**
 * Updates an existing Google Calendar event.
 */
export async function updateCalendarEvent(
  eventId: string,
  task: PlannerTask
): Promise<{ id: string; htmlLink?: string }> {
  const token = await ensureCalendarAccessToken();

  const [year, month, day] = task.date.split("-").map(Number);
  const startDateTime = new Date(year, month - 1, day, task.startHour, 0, 0);
  const endDateTime = new Date(year, month - 1, day, task.endHour, 0, 0);
  const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone || "UTC";

  const payload = {
    summary: `[atom-i] ${task.title}`,
    description: `${task.description || ""}\n\n• Focus Category: ${task.category.toUpperCase()}\n• Priority: ${task.priority.toUpperCase()}\n• Status: ${task.completed ? "COMPLETED" : "PLANNED"}\n\nGenerated by atom-i Tactical Operation Manager`,
    start: {
      dateTime: startDateTime.toISOString(),
      timeZone,
    },
    end: {
      dateTime: endDateTime.toISOString(),
      timeZone,
    },
  };

  const response = await fetch(`${CALENDAR_API_BASE}/calendars/primary/events/${encodeURIComponent(eventId)}`, {
    method: "PATCH",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.error?.message || "Failed to update Google Calendar event.");
  }

  const data = await response.json();
  return { id: data.id, htmlLink: data.htmlLink };
}

/**
 * Deletes a Google Calendar event.
 * Note: Must be guarded by an explicit user confirmation dialog.
 */
export async function deleteCalendarEvent(eventId: string): Promise<void> {
  const token = await ensureCalendarAccessToken();

  const response = await fetch(`${CALENDAR_API_BASE}/calendars/primary/events/${encodeURIComponent(eventId)}`, {
    method: "DELETE",
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  if (!response.ok && response.status !== 404) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.error?.message || "Failed to delete Google Calendar event.");
  }
}
